name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull abrarkhan1911/abrarapp

      - name: Delete old docker container
        run: sudo docker rm -f abrarpp-container || true

      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name abrarapp-container abrarkhan1911/abrarapp